// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PtEFLib
{

    // Color
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class ColorConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Color>
    {
        public ColorConfiguration()
            : this("dbo")
        {
        }

        public ColorConfiguration(string schema)
        {
            ToTable("Color", schema);
            HasKey(x => x.ColorId);

            Property(x => x.ColorId).HasColumnName(@"ColorId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.ColorName).HasColumnName(@"ColorName").HasColumnType("nvarchar").IsRequired().HasMaxLength(10);
        }
    }

}
// </auto-generated>
