// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PtEFLib
{

    // Option
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class OptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Option>
    {
        public OptionConfiguration()
            : this("dbo")
        {
        }

        public OptionConfiguration(string schema)
        {
            ToTable("Option", schema);
            HasKey(x => x.OptionId);

            Property(x => x.OptionId).HasColumnName(@"OptionId").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.OptionText).HasColumnName(@"OptionText").HasColumnType("nvarchar").IsRequired().HasMaxLength(150);
            Property(x => x.QuestionId).HasColumnName(@"QuestionId").HasColumnType("int").IsRequired();
            Property(x => x.Letter).HasColumnName(@"Letter").HasColumnType("char").IsRequired().IsFixedLength().IsUnicode(false).HasMaxLength(1);
        }
    }

}
// </auto-generated>
