// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace PtEFLib
{

    // Result
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.28.0.0")]
    public class ResultConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Result>
    {
        public ResultConfiguration()
            : this("dbo")
        {
        }

        public ResultConfiguration(string schema)
        {
            ToTable("Result", schema);
            HasKey(x => x.Letter);

            Property(x => x.Letter).HasColumnName(@"Letter").HasColumnType("nchar").IsRequired().IsFixedLength().HasMaxLength(1).HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.Character).HasColumnName(@"Character").HasColumnType("nvarchar(max)").IsRequired();
            Property(x => x.ColorId).HasColumnName(@"ColorId").HasColumnType("int").IsOptional();
        }
    }

}
// </auto-generated>
